version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '90:90'
      - '91:91'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - public
      - private

  subscription_core:
    build:
      context: ./subscription-core
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: subscription_core
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    networks:
      - private
    links:
      - pg
    volumes:
      - ./subscription-core:/app
      - /app/node_modules
    depends_on:
      pg:
        condition: service_healthy

  subscription_bff:
    build:
      context: ./subscription-bff
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: subscription_bff
    ports:
      - '5000:5000'
    restart: 'unless-stopped'
    networks:
      - public
      - redis
    volumes:
      - ./subscription-bff:/app
      - /app/node_modules
    depends_on:
      - subscription_core

  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '6379:6379'
    networks:
      - private
      - redis

  subscription_mailing:
    build:
      context: ./subscription-mailing
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: subscription_mailing
    ports:
      - '7000:7000'
    restart: 'unless-stopped'
    networks:
      - private
    volumes:
      - ./subscription-mailing:/app
      - /app/node_modules
    depends_on:
      kafka:
        condition: service_healthy

  pg:
    image: bitnami/postgresql:11-debian-10
    container_name: pg
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: test
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - private

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - private

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,INTERNAL_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,INTERNAL_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - private

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge
  redis:
    driver: bridge

volumes:
  data:
    driver: local
  database:
  subscription-core:
  subscription-bff:
  subscription-mailing:
  
